# Generated by Django 4.2.6 on 2023-10-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('idnumber', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
