# Generated by Django 4.2.6 on 2023-10-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_registrationrequest_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_description', models.CharField(max_length=1000)),
                ('notice_image', models.ImageField(upload_to='Files/Notice/')),
            ],
        ),
    ]
