# Generated by Django 4.2.6 on 2023-10-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1200)),
                ('location', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_photo', models.ImageField(upload_to='Files/Events/')),
                ('join_event', models.BooleanField(default=False)),
            ],
        ),
    ]
