# Generated by Django 4.2.6 on 2023-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('participated_at', models.DateTimeField(auto_now_add=True)),
                ('eventname', models.CharField(max_length=200)),
                ('eventdate', models.DateField()),
                ('eventtime', models.TimeField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
