# Generated by Django 4.2.6 on 2023-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='transaction_number',
            field=models.CharField(default='xxxxxxxxxxxxxxxxxx', max_length=20),
        ),
    ]
